[project]
name = "agentic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "google-news-feed>=1.1.0",
    "googlenewsdecoder>=0.1.7",
    "html2text>=2024.2.26",
    "jinja2>=3.1.5",
    "pyyaml>=6.0.2",
    "streamlit>=1.41.1",
    "swarm",
    "thespian>=3.10.7",
    "litellm",
    "googlenewsdecoder",
    "google_news_feed",
    "html2text",
    "typer",
]

[project.scripts]
agentic = "agentic.cli:app"

[tool.uv.sources]
swarm = { git = "https://github.com/scottpersinger/swarm.git" }
