#name: learn-github-actions

#on:
#  pull_request:
#    branches:
#      - main
#jobs:
#  run-pr-agent:
#    name: My first job
#    runs-on: ubuntu-latest
#    steps:
#      - name: Check out the repository to the runner
#        uses: actions/checkout@v4
#      - name: Install the latest version of uv
#        uses: astral-sh/setup-uv@v6
#      - name: Setup agentic
#        run: |
#          git clone git@github.com:supercog-ai/agentic.git
#          uv venv  --python 3.12
#          source .venv/bin/activate
          
          # For Linux or Windows
#          uv pip install -e "./agentic[all,dev]" --extra-index-url https://download.pytorch.org/whl/cpu --index-strategy unsafe-first-match
#      - name: Run pr review agent
#        run: |
#         py agent.py
#agent.finalresult() 
#look into deep researcher programatic workflow to open comment
#        env: 
#          super_secret: ${{ secrets.OpenAIKey }}
